# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='parent',
            new_name='created_by',
        ),
    ]
