# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161105_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='status',
        ),
        migrations.DeleteModel(
            name='ChildStatus',
        ),
    ]
